coco_keypoint_names = [
    "nose",
    "left_eye",
    "right_eye",
    "left_ear",
    "right_ear",
    "left_shoulder",
    "right_shoulder",
    "left_elbow",
    "right_elbow",
    "left_wrist",
    "right_wrist",
    "left_hip",
    "right_hip",
    "left_knee",
    "right_knee",
    "left_ankle",
    "right_ankle",
]

coco_keypoint_connections = [
    [16, 14],
    [14, 12],
    [17, 15],
    [15, 13],
    [12, 13],
    [6, 12],
    [7, 13],
    [6, 7],
    [6, 8],
    [7, 9],
    [8, 10],
    [9, 11],
    [2, 3],
    [1, 2],
    [1, 3],
    [2, 4],
    [3, 5],
    [4, 6],
    [5, 7],
]

drive_and_act_keypoint_names = [
    "nose",
    "lEye",
    "rEye",
    "lEar",
    "rEar",
    "lShoulder",
    "rShoulder",
    "lElbow",
    "rElbow",
    "lWrist",
    "rWrist",
    "lHip",
    "rHip",
    "lKnee",
    "rKnee",
    "lAnkle",
    "rAnkle",
]

all_drive_and_act_keypoint_names = [
    'nose', 'lElbow', 'lWrist', 'rHeel', 'rHip',
    'rSmallToe', 'neck', 'lSmallToe', 'rWrist',
    'rAnkle', 'lHip', 'lHeel', 'lKnee', 'lEye',
    'midHip', 'background', 'lEar', 'rElbow',
    'rShoulder', 'rKnee', 'lShoulder', 'lBigToe',
    'rEye', 'rEar', 'rBigToe', 'lAnkle'
]
